Tries to fork zygote using android.os.Process.start() which is not part of the official SDK and therefor has to be called using reflection (not the way to go)
Also, it does not work
E/Process: Starting VM process through Zygote failed
java.io.IOException: Permission denied